service:
  golangci-lint-version: 1.21.0

run:
  timeout: 5m
  skip-files:
     - example.*.go
     - server/manifest.go
  skip-dirs:
    - build/

linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - scopelint
    - staticcheck
    - structcheck
    - unconvert
    - unused
    - varcheck

linters-settings:
  gofmt:
    simplify: true
  govet:
    check-shadowing: true
    enable-all: true
  goimports:
    local-prefixes: github.com/mattermost/mattermost-plugin-api

issues:
  exclude-rules:
    # Exclude some linters from running on tests files.
    - path: _test\.go
      linters:
        - goconst
        - scopelint # https://github.com/kyoh86/scopelint/issues/4
        - unparam
    - linters:
      - golint
      - gocritic
      path: "server/bot/logger.go"
