version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.1
  codecov: codecov/codecov@1.1.1

aliases:
  - &restore_cache
    restore_cache:
      key: go-mod-v1-{{ checksum "go.sum" }}
  - &save_cache
    save_cache:
      key: go-mod-v1-{{ checksum "go.sum" }}
      paths:
        - "/go/pkg/mod"

jobs:
  coverage-with-db:
    docker:
      - image: circleci/golang:1.14.1-node
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: mmuser
          POSTGRES_DB: mattermost_test
      - image: circleci/mysql:5.6
        environment:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
    executor:
      name: plugin-ci/default
    steps:
      - run:
          name: Waiting for Postgres and MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres and MySQL && exit 1
      - checkout
      - *restore_cache
      - run:
          name: Generating Coverage Results
          command: make coverage
      - *save_cache
      - codecov/upload:
        file: server/coverage.txt

workflows:
  version: 2
  ci:
    jobs:
      - plugin-ci/lint:
          filters:
            tags:
              only: /^v.*/
      - coverage-with-db:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/build:
          filters:
            tags:
              only: /^v.*/
      - plugin-ci/deploy-ci:
          filters:
            branches:
              only: master
          context: plugin-ci
          requires:
            - plugin-ci/lint
            - coverage-with-db
            - plugin-ci/build
      - plugin-ci/deploy-release:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: plugin-ci
          requires:
            - plugin-ci/lint
            - coverage-with-db
            - plugin-ci/build
      - plugin-ci/deploy-release-github:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          context: matterbuild-github-token
          requires:
            - plugin-ci/lint
            - coverage-with-db
            - plugin-ci/build
