version: 2.1

orbs:
  plugin-ci: mattermost/plugin-ci@0.1
  codecov: codecov/codecov@1.1.1
  cypress: cypress-io/cypress@1

aliases:
  - &restore_cache
    restore_cache:
      key: go-mod-v1-{{ checksum "go.sum" }}
  - &save_cache
    save_cache:
      key: go-mod-v1-{{ checksum "go.sum" }}
      paths:
        - "/go/pkg/mod"

jobs:
  coverage-MySQL56-Postgres96:
    docker:
      - image: circleci/golang:1.14.1-node
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: mmuser
          POSTGRES_DB: mattermost_test
      - image: circleci/mysql:5.6.49
        environment:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
    executor:
      name: plugin-ci/default
    steps:
      - run:
          name: Waiting for Postgres and MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres and MySQL && exit 1
      - checkout
      - *restore_cache
      - run:
          name: Generating Coverage Results
          command: make coverage
      - *save_cache
      - codecov/upload:
        file: server/coverage.txt

  test-MySQL57-Postgres10:
    docker:
      - image: circleci/golang:1.14.1-node
      - image: circleci/postgres:10.9-alpine
        environment:
          POSTGRES_USER: mmuser
          POSTGRES_DB: mattermost_test
      - image: circleci/mysql:5.7.31
        environment:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
    executor:
      name: plugin-ci/default
    steps:
      - run:
          name: Waiting for Postgres and MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres and MySQL && exit 1
      - checkout
      - *restore_cache
      - run:
          name: Testing
          command: make test
      - *save_cache

  test-MySQL8-Postgres11:
    docker:
      - image: circleci/golang:1.14.1-node
      - image: circleci/postgres:11.6-alpine
        environment:
          POSTGRES_USER: mmuser
          POSTGRES_DB: mattermost_test
      - image: circleci/mysql:8.0.21
        environment:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
    executor:
      name: plugin-ci/default
    steps:
      - run:
          name: Waiting for Postgres and MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres and MySQL && exit 1
      - checkout
      - *restore_cache
      - run:
          name: Testing
          command: make test
      - *save_cache

  test-MySQL-Postgres-latest:
    docker:
      - image: circleci/golang:1.14.1-node
      - image: circleci/postgres:latest
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_USER: mmuser
          POSTGRES_DB: mattermost_test
      - image: circleci/mysql:latest
        environment:
          MYSQL_ROOT_PASSWORD: mostest
          MYSQL_DATABASE: mattermost_test
          MYSQL_USER: mmuser
          MYSQL_PASSWORD: mostest
    executor:
      name: plugin-ci/default
    steps:
      - run:
          name: Waiting for Postgres and MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && nc -z 127.0.0.1 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres and MySQL && exit 1
      - checkout
      - *restore_cache
      - run:
          name: Testing
          command: make test
      - *save_cache

  e2e-cypress-tests:
    docker:
      - image: circleci/golang:1.14.1-node-browsers
        environment:
          TEST_DATABASE_URL: postgres://mmuser:mostest@localhost:5432/mattermost_test
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: mmuser
          POSTGRES_PASSWORD: mostest
          POSTGRES_DB: mattermost_test
      - image: jhillyerd/inbucket:release-1.2.0
      - image: minio/minio:RELEASE.2019-10-11T00-38-09Z
        command: "server /data"
        environment:
          MINIO_ACCESS_KEY: minioaccesskey
          MINIO_SECRET_KEY: miniosecretkey
          MINIO_SSE_MASTER_KEY: "my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574"
      - image: mattermost/mattermost-elasticsearch-docker:6.5.1
        environment:
          http.host: "0.0.0.0"
          http.port: 9200
          http.cors.enabled: "true"
          http.cors.allow-origin: "http://localhost:1358,http://127.0.0.1:1358"
          http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
          http.cors.allow-credentials: "true"
          transport.host: "127.0.0.1"
          ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      - image: mattermost/mattermost-enterprise-edition:$MM_DOCKER_IMAGE_TAG
        environment:
          DB_HOST: localhost
          DB_PORT_NUMBER: 5432
          MM_DBNAME: mattermost_test
          MM_USERNAME: mmuser
          MM_PASSWORD: mostest
          CI_INBUCKET_HOST: localhost
          CI_INBUCKET_PORT: 10080
          CI_MINIO_HOST: minio
          IS_CI: true
          MM_CLUSTERSETTINGS_READONLYCONFIG: false
          MM_EMAILSETTINGS_SMTPSERVER: localhost
          MM_EMAILSETTINGS_SMTPPORT: 10025
          MM_ELASTICSEARCHSETTINGS_CONNECTIONURL: http://localhost:9200
          MM_EXPERIMENTALSETTINGS_USENEWSAMLLIBRARY: true
          MM_SQLSETTINGS_DATASOURCE: "postgres://mmuser:mostest@localhost:5432/mattermost_test?sslmode=disable&connect_timeout=10"
          MM_SQLSETTINGS_DRIVERNAME: postgres
          MM_PLUGINSETTINGS_ENABLEUPLOADS: true
          MM_SERVICESETTINGS_ENABLETESTING: true
          MM_SERVICESETTINGS_ENABLEDEVELOPER: true
    environment:
      MM_DOCKER_IMAGE_TAG: master
      TYPE: NONE
      PULL_REQUEST:
      BROWSER: chrome
      HEADLESS: true
      DASHBOARD_ENABLE: false
      FULL_REPORT: false
      MM_SERVICESETTINGS_SITEURL: http://localhost:8065
      MM_ADMIN_USERNAME: sysadmin
      MM_ADMIN_PASSWORD: Sys@dmin-sample1
    steps:
      - setup_remote_docker
      - run:
          name: Wait for Inbucket
          command: |
            until curl --max-time 5 --output - localhost:10080; do echo waiting for Inbucket; sleep 5; done;
      - run:
          name: Wait for Elasticsearch
          command: |
            until curl --max-time 5 --output - localhost:9200; do echo waiting for Elasticsearch; sleep 5; done;
      - checkout
      - attach_workspace:
          at: ~/mattermost-cypress-docker
      - run:
          name: Set and restore Postgres DB
          command: |
            whoami
            sudo apt-get update
            sudo apt-get install libxss1
            sudo apt-get install postgresql-client
            psql -d $TEST_DATABASE_URL -c "CREATE DATABASE migrated;"
            psql -d $TEST_DATABASE_URL -c "CREATE DATABASE latest;"
            psql -d $TEST_DATABASE_URL mattermost_test < tests-e2e/db-setup/test_data.sql
#            psql -d $TEST_DATABASE_URL -c "DELETE FROM licenses WHERE id='$EE_LICENSE_ID';"
#            psql -d $TEST_DATABASE_URL -c "INSERT INTO licenses (id, createat, bytes) VALUES ('$EE_LICENSE_ID','1589175893083','$EE_LICENSE');"
#            psql -d $TEST_DATABASE_URL -c "DELETE FROM systems WHERE name='ActiveLicenseId';"
#            psql -d $TEST_DATABASE_URL -c "INSERT INTO systems (name, value) VALUES ('ActiveLicenseId', '$EE_LICENSE_ID');"
#      - run:
#          name: Setup required files
#          command: |
#            echo $EE_LICENSE > e2e/cypress/fixtures/mattermost-license.txt
#            echo $SAML_IDP_CRT | base64 --decode > e2e/cypress/fixtures/saml-idp.crt
#            echo $SAML_PRIVATE_KEY | base64 --decode > e2e/cypress/fixtures/saml-private.key
#            echo $SAML_PUBLIC_CRT | base64 --decode > e2e/cypress/fixtures/saml-public.crt
#            wget -O e2e/cypress/fixtures/com.mattermost.draw-plugin.tar.gz https://github.com/jespino/mattermost-plugin-draw/releases/download/v0.0.4/com.mattermost.draw-plugin-0.0.4.tar.gz
#            wget -O e2e/cypress/fixtures/com.github.matterpoll.matterpoll.tar.gz https://github.com/matterpoll/matterpoll/releases/download/v1.3.0/com.github.matterpoll.matterpoll-1.3.0.tar.gz
#            wget -O e2e/cypress/fixtures/com.mattermost.demo-plugin-0.1.0.tar.gz https://github.com/mattermost/mattermost-plugin-demo/releases/download/v0.1.0/com.mattermost.demo-plugin-0.1.0.tar.gz
#            wget -O e2e/cypress/fixtures/com.mattermost.demo-plugin-0.2.0.tar.gz https://github.com/mattermost/mattermost-plugin-demo/releases/download/v0.2.0/com.mattermost.demo-plugin-0.2.0.tar.gz
      - run:
          name: Install IR plugin
          command: make deploy
#      - run:
#          name: Install npm packages
#          command: cd e2e && npm install
#      - save_cache: # special step to save the dependency cache
#          key: dependency-cache-{{ checksum "e2e/package-lock.json" }}
#          paths:
#            - ./e2e/node_modules
      - cypress/run:
          name: Run Cypress Tests
          working-directory: tests-e2e
#          no_output_timeout: 30m
#          command: |
#            export FAILURE_MESSAGE="At least one test has failed."
#            export RESULTS_OUTPUT="results-output.txt"
#            npm run test
#            cd e2e && nohup node webhook_serve.js > webhook_serve.log &
#            export CYPRESS_chromeWebSecurity=true
#            export CYPRESS_dbClient=postgres
#            export CYPRESS_dbConnection="postgres://mmuser:mostest@localhost:5432/mattermost_test?sslmode=disable&connect_timeout=10"
#            export CYPRESS_resetBeforeTest=true
#            export CYPRESS_runLDAPSync=false
#            cd e2e && node run_tests.js --stage='@prod' |& tee $RESULTS_OUTPUT; if grep "$FAILURE_MESSAGE" "$RESULTS_OUTPUT"; then exit 1; fi
#      - run:
#          name: Save and publish reports
#          when: always
#          command: |
#            export DIAGNOSTIC_USER_ID=`psql -d $TEST_DATABASE_URL -t -c "SELECT id FROM users WHERE username='sysadmin';"`
#            export DIAGNOSTIC_TEAM_ID=`psql -d $TEST_DATABASE_URL -t -c "SELECT id FROM teams WHERE name='ad-1';"`
#            export BRANCH=$CIRCLE_BRANCH
#            export BUILD_ID=$CIRCLE_BUILD_NUM
#            # This is how it should be on main org repo
#            # export PULL_REQUEST=$CIRCLE_PULL_REQUESTS
#            # This is how it should be on main org repo
#            # Should match the tag in mattermost/mattermost-enterprise-edition image
#            # export BUILD_TAG="${CIRCLE_SHA1:0:7}"
#            export BUILD_TAG=$MM_DOCKER_IMAGE_TAG
#            cd e2e && node save_report.js

workflows:
  version: 2
  ci:
    jobs:
#      - plugin-ci/lint:
#          filters:
#            tags:
#              only: /^v.*/
#      - coverage-MySQL56-Postgres96:
#          filters:
#            tags:
#              only: /^v.*/
#      - test-MySQL57-Postgres10:
#          filters:
#            tags:
#              only: /^v.*/
#      - test-MySQL8-Postgres11:
#          filters:
#            tags:
#              only: /^v.*/
#      - test-MySQL-Postgres-latest:
#          filters:
#            tags:
#              only: /^v.*/
      - e2e-cypress-tests:
          context: cypress-circleci-env
          filters:
            tags:
              only: /^v.*/
#      - plugin-ci/build:
#          filters:
#            tags:
#              only: /^v.*/
#      - plugin-ci/deploy-ci:
#          filters:
#            branches:
#              only: master
#          context: plugin-ci
#          requires:
#            - plugin-ci/lint
#            - coverage-MySQL56-Postgres96
#            - test-MySQL57-Postgres10
#            - test-MySQL8-Postgres11
#            - test-MySQL-Postgres-latest
#            - e2e-cypress-tests
#            - plugin-ci/build
#      - plugin-ci/deploy-release:
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
#          context: plugin-ci
#          requires:
#            - plugin-ci/lint
#            - coverage-MySQL56-Postgres96
#            - test-MySQL57-Postgres10
#            - test-MySQL8-Postgres11
#            - test-MySQL-Postgres-latest
#            - plugin-ci/build
#      - plugin-ci/deploy-release-github:
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
#          context: matterbuild-github-token
#          requires:
#            - plugin-ci/lint
#            - coverage-MySQL56-Postgres96
#            - test-MySQL57-Postgres10
#            - test-MySQL8-Postgres11
#            - test-MySQL-Postgres-latest
#            - plugin-ci/build
